### PR TITLE
ElmishPlanets --> FabulousPlanets

### PR DESCRIPTION
**Pull request by dsyme**
@TimLariviere Rename to FabPlanets.  

Would you prefer FabulousPlanets?  I just figured it might be better to use Fab for apps (to distinguish from future libraries like `Fabulous.Planets` :) ), but on second consideration maybe the former name is better, partly to align with FabulousContacts.

### CODE REVIEW

**Comment by TimLariviere** [comment]
I do like `FabulousPlanets` and `FabulousContacts`.
It's both more explicit that those apps are using Fabulous, and a good play on word (planets are fabulous, and so I hope my contacts are, at least some of them... 😄).

I think we're safe regarding name collision with `Fabulous.Planets`. (who knows...)
`Fabulous.Contacts` on the other hand maybe more likely, but hopefully it would be easy enough to figure out `FabulousContacts` is not `Fabulous.Contacts` :)

**Comment by dsyme** [comment]
ok will rename to FabulousPlanets

**Comment by dsyme** [comment]
Ready

**Comment by TimLariviere** [comment]
Thank you!

**Pull request merged**
